from contractor.models import BreakingChange
from datetime import datetime, timezone


def to_markdown(
    changes: list[BreakingChange], base_path: str, candidate_path: str
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if not changes:
        return (
            "## Contractor -- No Breaking Changes\n\n"
            f"Comparing `{base_path}` -> `{candidate_path}`\n\n"
            f"*Generated by [Contractor](https://contractor.dev) · {now}*\n"
        )

    lines = [
        f"## Contractor -- {len(changes)} Breaking Change{'s' if len(changes) != 1 else ''} Detected",
        "",
        f"Comparing `{base_path}` -> `{candidate_path}`",
        "",
        "> Warning: This PR introduces breaking API changes. Review before merging.",
        "",
        "| Type | Location | Description |",
        "|------|----------|-------------|",
    ]

    kind_labels = {
        "endpoint_removed": "Endpoint removed",
        "required_param_added": "Required param added",
        "type_changed": "Type changed",
        "required_field_added": "Required field added",
    }

    for c in changes:
        label = kind_labels.get(c.kind, c.kind)
        lines.append(f"| {label} | `{c.location}` | {c.description} |")

    lines += [
        "",
        f"*Generated by [Contractor](https://contractor.dev) · {now}*",
    ]

    return "\n".join(lines) + "\n"
